# site properties and page defaults
title: Tatsuya Murakami
subtitle:
description: My research aims to understand the pathogenic mechanisms underlying neurological disorders. We integrate 3D single-cell-resolution imaging with deep learning, focusing on developing a suite of tools to standardize the human brain anatomy at the cellular level. 
header: images/photo_embryo.jpg
footer: images/background_brain.jpg
proofer: false

# site social media and other links
links:
  orcid: 0000-0002-3734-9359
  google-scholar: dQKJ9ZgAAAAJ
  github: tatz-murakami
  twitter: TatzMurakami
#  youtube: tatz-murakami

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
  
darkmode:
  enable_dark_mode: true
  show_dark_mode_toggle_in_header: true 
  show_dark_mode_toggle_in_bottom: false # displays the dark mode toggle switch in the footer and allows the user to manually change the mode
  show_dark_mode_toggle_in_mobile_menu: false # displays the dark mode toggle switch in the footer and allows the user to manually change the mode
