# site properties and page defaults
title: Tatsuya Murakami
subtitle: 
description: The Murakami research group focuses on developing a suite of research tools to standardize the cellular neuroanatomy of the human brain. Our goal is to understand the cellular pathogenic mechanisms underlying neurodevelopmental disorders. We integrate 3D single-cell-resolution imaging with deep learning to quantitatively evaluate how the brain is affected by developmental disorders at the cellular level. 
header: images/background_brain.jpg
footer: images/background_brain.jpg
proofer: false

# site social media and other links
links:
  email: tmurakami@rockefeller.edu
  orcid: 0000-0002-3734-9359
  google-scholar: dQKJ9ZgAAAAJ
  github: tatz-murakami
  twitter: TatzMurakami
#  youtube: tatz-murakami

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
